### PR TITLE
Adding basic badges

### PR DESCRIPTION
**Pull request by penrods**
Adding basic badges to help those browsing the repo to understand where it is as development project.

### CODE REVIEW

**Comment by krisgesling** [comment]
Looks good to me. 

Have either of you had thoughts about a preferred license?

**Review by skraynick — APPROVED** [review]
DItto. @krisgesling that is a question for @penrods... I have my preference, but I will leave it to the boss..

**Comment by penrods** [comment]
My preference here is always Apache 2.0+CLA.  Many of my thoughts are as to why are laid out here:. https://mycroft.ai/blog/right-license/

I'm happy to discuss as this does have some technical impact with regard to which libraries you can use, etc.

**Comment by krisgesling** [comment]
Just saw that this was still outstanding. Will merge this and can add an explicit license later.

**Pull request merged**
